# This workflow will upload a Python Package using Twine when a release is created
# For more information see: https://help.github.com/en/actions/language-and-framework-guides/using-python-with-github-actions#publishing-to-package-registries

# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

name: Upload Python Package to Test-PyPI

env:
  PYTHON_MAIN_VERSION: 3.10
  POETRY_VERSION: 1.2.2

on:
  release:
    types: [published]

jobs:
  deploy:
    name: Test on ${{ matrix.os}}
    runs-on: ${{ matrix.os}}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest]

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.10'
        
    - name: Install dependencies
      run: |
        python -m pip install poetry==${{ env.POETRY_VERSION }}
        poetry install
        
    - name: Build Python package and Upload to TestPyPi
      env:
          TEST_PYPI_TOKEN: ${{ secrets.TEST_PYPI }}
      run: |
          poetry update
          poetry build
          poetry config repositories.testpypi https://test.pypi.org/legacy/
          poetry publish -r testpypi --username "__token__" --password $TEST_PYPI_TOKEN
